# https://travis-ci.org/
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
env:
  - RUN_SCRIPT=native-notadded-node
  - RUN_SCRIPT=native-notadded-only
  - RUN_SCRIPT=polyfill-notadded-node
  - RUN_SCRIPT=polyfill-notadded-only
  - RUN_SCRIPT=cross-notadded-node
  - RUN_SCRIPT=cross-notadded-only
  - RUN_SCRIPT=cross-notadded-node-cwd-child
  - RUN_SCRIPT=shebang-node
  - RUN_SCRIPT=shebang-only
script: "npm run run-linux"
