# http://www.appveyor.com/docs/appveyor-yml

# init
clone_depth: 20

environment:
  matrix:
  - RUN_SCRIPT: native-notadded-node
  - RUN_SCRIPT: native-notadded-only
  - RUN_SCRIPT: polyfill-notadded-node
  - RUN_SCRIPT: polyfill-notadded-only
  - RUN_SCRIPT: cross-notadded-node
  - RUN_SCRIPT: cross-notadded-only
  - RUN_SCRIPT: cross-notadded-node-cwd-child
  - RUN_SCRIPT: cross-notadded-only-cwd-child
  - RUN_SCRIPT: shebang-node
  - RUN_SCRIPT: shebang-only

# install
install:
- node --version
- npm --version
- npm install

# build
build: off

# test
test_script:
- npm run run-windows

# deploy
deploy: off

# notify
notifications:
- provider: Email
  to:
  - o.gata.ken@gmail.com
  on_build_status_changed: true
